# Generated by Django 5.0.6 on 2024-06-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('smart Phone', 'smart Phone'), ('Tablet', 'Tablet'), ('Smart Watch', 'Smart Watch'), ('Laptop', 'Laptop')], max_length=200),
        ),
    ]
