# Generated by Django 5.0.6 on 2024-06-02 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Smart Phone', 'Smart Phone'), ('Tablet', 'Tablet'), ('Smart Watch', 'Smart Watch'), ('Laptop', 'Laptop')], max_length=200),
        ),
    ]
