# Generated by Django 5.0.6 on 2024-06-02 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('smart phone', 'smart phone'), ('tablets', 'tablets'), ('smart watches', 'smart watches'), ('laptops', 'laptops')], max_length=200),
        ),
    ]
