# Generated by Django 5.0.6 on 2024-06-05 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_cart_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(default='added', max_length=200),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(default='order placed', max_length=200),
        ),
    ]
